version: '3.4'

services:
  web:
    image: StudentManagmentSystem  
    build:
      context: .
      dockerfile: StudentManagmentSystem/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - app_db

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psdev98
      - POSTGRES_DB=ps-student2
    ports:
      - "5433:5432"
